### ISSUE TITLE
I want to ask you, the design idea of your  GeneticNAS algorithm

### ISSUE THREAD

**Issue by zhanghaoyu000** [haihabi/GNAS#1]
Excuse me , I'm sorry to trouble you.
I am a graduate student of donghua university of China.
I want to ask you, the design idea of your  GeneticNAS algorithm, for example ,the paper you published or  references, specification of algorithm and so on.
If I don't have this information, I can't understand your code. thank you .
It would be my great honor if you could give me these information.  my E-mail address is zhy920816@sina.cn .
thanke you very very much

**Comment by haihabi** [comment]
Hi,
I hope to publish this work on Arxiv in the next couple of weeks.

**Comment by haihabi** [comment]
Hi, please see the following link:https://arxiv.org/pdf/1907.02871.pdf
