### ISSUE TITLE
Where can i find the full architecture in the pkl or pth files ? And how do i load it ?

### ISSUE THREAD

**Issue by cristyioan2000** [haihabi/GNAS#2]
Hello, I'm a computer science graduate engineer and I've been testing multiple NAS methods. Great work you did with this Genetic approach. I am trying to find a model on a custom dataset and use the found architecture. How can I load the architecture in a PyTorch model ? Do I need to reconstruct the cells found in log.txt and manually build the model ? Is there a way to directly extract the final model and load it into a PyTorch model without manually building the model ? When I say mode I refer to the layers not the weight tensor, the layers in the nn.Modules / nn.Sequential. Thank you !

**Comment by haihabi** [comment]
The best model config is saved to the file best_individual.pickle, which can be loaded later using the following command:load_final(net, args.search_dir) which imported from common import load_final

I hope this answers your question

**Comment by cristyioan2000** [comment]
Is there a way to visualize the entire architecture of the best individual ? I've tried to print the layers of the network using summary(net,(3,32,32)) but I think the format of the network is not supported by torchsummary lib.  I want to load the architecture to other python script but i have no idea how to decode the current format. That's because of the repeat blocks.

**Comment by haihabi** [comment]
You can use the model function set_individual to set the current model architecture? 
The common function load_final, loads the pickle file and call this function please see the following code:
ind_file = os.path.join(search_dir, 'best_individual.pickle')
ind = pickle.load(open(ind_file, "rb"))
model.set_individual(ind)

This that answers your question? If not can you please show me an example of the wanted output?

**Comment by cristyioan2000** [comment]
I'm sorry if the question is not very clear, I would want to know how to:

1. Load the model's architecture (layers and structure example: `model = Some_Model_Class()` but from a file if possible without the class ) + `load_individual(ind)` to replace the RepeatBlocks and ReductionBlocks from the network
2. Load the model's weights 
3. Give the network some input and get the output

So in a few words I would like to import the whole model in another python script file and infer/test it. And I don't know if I can recreate the model without the :
```
net = model_cnn.Net(config.get('n_blocks'), config.get('n_channels'), n_param,
                        config.get('dropout'),
                        ss, aux=config.get('aux_loss')).to(working_device)
```

So I used **trained_search.py** and I got **best_individual.pickle**, **best_model.pt** , **ga_result.pickle** . My guess is that i can't to this :

```
model = torch.load(os.path.join(self.search_dir, 'best_model.pt'))
        model.set_individual(ind)
```
Because the **best_model.pt** was created like this :
`torch.save(net.state_dict(), os.path.join(log_dir, 'best_model.pt'))`
And there is no class stored in the file just the `state_dict()` which is the weight file as far as I know.

```
import os
import torch
from common import *
import pickle
from torchsummary import summary

class Found_Architecture():
    def __init__(self):
        self.search_dir = r'/home/lbularca/Desktop/GeneticNAS/logs/2019_08_13_09_53_58/'
        # some random data like Cifar10 images
        self.generic_data_list = list()
    def _load_found_architecture_(self):
        ind_file = os.path.join(self.search_dir, 'best_individual.pickle')
        ind = pickle.load(open(ind_file, "rb"))
        ### How do I get my model ? 
        model = torch.load(os.path.join(self.search_dir, 'best_model.pt'))
        model.set_individual(ind)
        # Test data for found architecture
        for data_sample in self.generic_data_list:
            outs = model(data_sample) # data_sample == inputs 
            print(outs)


        # MODEL ARCHITRECTURE #
        '''
        net = model_cnn.Net(config.get('n_blocks'), config.get('n_channels'), n_param,
                        config.get('dropout'),
                        ss, aux=config.get('aux_loss')).to(working_device)
                        '''
architecture_obj = Found_Architecture()
architecture_obj._load_found_architecture_()
```

And the output is 

```
Traceback (most recent call last):
  File "/home/lbularca/.vscode/extensions/ms-python.python-2019.6.24221/pythonFiles/ptvsd_launcher.py", line 43, in <module>
    main(ptvsdArgs)
  File "/home/lbularca/.vscode/extensions/ms-python.python-2019.6.24221/pythonFiles/lib/python/ptvsd/__main__.py", line 434, in main
    run()
  File "/home/lbularca/.vscode/extensions/ms-python.python-2019.6.24221/pythonFiles/lib/python/ptvsd/__main__.py", line 312, in run_file
    runpy.run_path(target, run_name='__main__')
  File "/home/lbularca/anaconda3/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/home/lbularca/anaconda3/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/home/lbularca/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/lbularca/Desktop/GeneticNAS/rebuildNET.py", line 30, in <module>
    architecture_obj._load_found_architecture_()
  File "/home/lbularca/Desktop/GeneticNAS/rebuildNET.py", line 16, in _load_found_architecture_
    model.set_individual(ind)
AttributeError: 'collections.OrderedDict' object has no attribute 'set_individual'
```

1.Where do I get my model from ? 
Using 
```
net = model_cnn.Net(config.get('n_blocks'), config.get('n_channels'), n_param,
                        config.get('dropout'),
                        ss, aux=config.get('aux_loss')).to(working_device)
```
Or there is another way ? 

2. If you want to test some dataset with the found architecture how do you proceed ? How do you load your model and import everything you need to test the new data ?

**Comment by haihabi** [comment]
Now I understand better please see my comments here:
1. The function "model = torch.load(os.path.join(self.search_dir, 'best_model.pt'))" only loads an OrderedDict of the weights If we want you cant try to save and load the model class to pickle file but I am not sure this will work with pytorch modules.
2. Usually the model in pytorch define by code:
net = model_cnn.Net(config.get('n_blocks'), config.get('n_channels'), n_param,
                        config.get('dropout'),ss, aux=config.get('aux_loss')).to(working_device) 
net.set_individual(ind)
3. You can easly build code for this: 
net = model_cnn.Net(config.get('n_blocks'), config.get('n_channels'), n_param,
                        config.get('dropout'),
                        ss, aux=config.get('aux_loss')).to(working_device)
load_final(net, args.search_dir)
state_dict=torch.load(os.path.join(self.search_dir, 'best_model.pt'))
net.load_state_dict(state_dict)

Now run you dataset on Net

**Comment by cristyioan2000** [comment]
I've run this code and it seems to work. It builds the model, replaces the generic cells with the found cells and loads the weights. At the end it tests the whole architecture on some CIFAR10 data samples. 
```
import os
import torch
from common import *
import pickle
from torchsummary import summary
from models import model_cnn
from config import get_config, load_config, save_config
import gnas
from data import get_dataset
from modules.drop_module import DropModuleControl
import torchvision
import torchvision.transforms as transforms


class Found_Architecture():
    def __init__(self):
        self.search_dir = r'/home/lbularca/Desktop/GeneticNAS/logs/2019_08_06_14_20_48/'
        # some random data like Cifar10 images
        self.generic_data_list = list()
    #######################################
    # Rebulding the backbone of the ConvNet without replacing the cells
    #######################################
    def _rebuild_(self):
        print("=================> Creating Model..\n")
        self.working_device = torch.device("cuda" if torch.cuda.is_available() else quit())
        model_type = get_model_type(dataset_name='CIFAR10')
        config = get_config(model_type)
        #trainloader, testloader, n_param = get_dataset(config)
        n_param = 10
        min_objective = False
        n_cell_type = gnas.SearchSpaceType(config.get('n_block_type') - 1)
        dp_control = DropModuleControl(config.get('drop_path_keep_prob'))
        ss = gnas.get_gnas_cnn_search_space(config.get('n_nodes'), dp_control, n_cell_type)

        net = model_cnn.Net(config.get('n_blocks'), config.get('n_channels'), n_param,
                            config.get('dropout'),
                            ss, aux=config.get('aux_loss')).to(self.working_device)
        print("=================> Crated Successfully!\n")

        return net
    def _load_found_architecture_(self):
        print("=================> Load found architecture..\n")

        # Load model's architecture
        model =self._rebuild_()
        # Load cell's genotype from pickle file
        ind_file = os.path.join(self.search_dir, 'best_individual.pickle')
        # Load cells -NORMAL- -REDUCTION-
        ind = pickle.load(open(ind_file, "rb"))
        model.set_individual(ind)
        model_weights = torch.load(os.path.join(self.search_dir, 'best_model.pt'))
        model.load_state_dict(model_weights)
        print("=================> Architecture Loaded Succesfully!\n")

        return model
        #summary(model,(3,32,32))
        # print(model)
        # Test data for found architecture
        # for data_sample in self.generic_data_list:
        #     outs = model(data_sample) # data_sample == inputs 
        #     print(outs)


        # MODEL ARCHITRECTURE #
        '''
        net = model_cnn.Net(config.get('n_blocks'), config.get('n_channels'), n_param,
                        config.get('dropout'),
                        ss, aux=config.get('aux_loss')).to(working_device)
                        '''
    def _test_(self,model):
        print("=================> Testing Model..")

        model = model.to(self.working_device)
        transform = transforms.Compose(
            [transforms.ToTensor(),
            transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))]
            )

        trainset = torchvision.datasets.CIFAR10(root='./data', train=True,
                                                download=True, transform=transform)
        trainloader = torch.utils.data.DataLoader(trainset, batch_size=4,
                                                shuffle=True, num_workers=2)

        testset = torchvision.datasets.CIFAR10(root='./data', train=False,
                                            download=True, transform=transform)
        testloader = torch.utils.data.DataLoader(testset, batch_size=4,
                                                shuffle=False, num_workers=2)

        classes = ('plane', 'car', 'bird', 'cat',
                'deer', 'dog', 'frog', 'horse', 'ship', 'truck')
       

        correct = 0
        total = 0
        with torch.no_grad():
            for data in testloader:
                images, labels = data
                
                images = images.to(self.working_device)
                labels = labels.to(self.working_device)
                
                outputs = model(images)
                _, predicted = torch.max(outputs[0].data, 1)
                total += labels.size(0)
                correct += (predicted == labels).sum().item()

        print('Accuracy of the network on the 10000 test images: %d %%' % (
            100 * correct / total))



architecture_obj = Found_Architecture()
network = architecture_obj._load_found_architecture_()
architecture_obj._test_(network)

```
### OUTPUT:

```
=================> Load found architecture..

=================> Creating Model..

=================> Crated Successfully!

=================> Architecture Loaded Succesfully!

=================> Testing Model..
Files already downloaded and verified
Files already downloaded and verified
Accuracy of the network on the 10000 test images: 70 %
```
I've tried with a custom ConvNet( basic convolutional network) to save the model in a checkpoint and load it successfully later with this code:
```
# Saves the model in a pth file 
def _save_policy_(model,epoch,optimizer,loss):

  checkpoint = {
  'model': ConvNet(),
  'state_dict': model.state_dict(),
  'optimizer_state':optimizer.state_dict(),
  'epoch':epoch,
  'optimizer': optimizer,
  'loss':loss
               }
  torch.save(checkpoint,"ConvNet_{}.pth".format(epoch))

checkpoint = torch.load('ConvNet_2.pth')
model = checkpoint['model']
model.load_state_dict(checkpoint['state_dict'])
```
I'm going to try to do the same with this GeneticNAS method. 

Thank you for your time and patience!

**Comment by mlizhardy** [comment]
> Is there a way to visualize the entire architecture of the best individual ? I've tried to print the layers of the network using summary(net,(3,32,32)) but I think the format of the network is not supported by torchsummary lib. I want to load the architecture to other python script but i have no idea how to decode the current format. That's because of the repeat blocks.

you can use netron.app to visualize the forward pass

**Comment by chrischan0204** [comment]
Hello, there.
I want to know the net structure from pth weights file and how can you help me?
